language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '6'
script:
  - node node_modules/.bin/prettier -l "*.{js,json,md}"
  - npm test
branches:
  only:
    - master
    - /^greenkeeper/.*$/
